
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox13;

	private global::Gtk.Entry entry3;

	private global::Gtk.HBox hbox39;

	private global::Gtk.VBox vbox14;

	private global::Gtk.Button button53;

	private global::Gtk.Button button61;

	private global::Gtk.VBox vbox22;

	private global::Gtk.Button button65;

	private global::Gtk.Button button69;

	private global::Gtk.Button button73;

	private global::Gtk.HBox hbox41;

	private global::Gtk.VBox vbox16;

	private global::Gtk.Button button55;

	private global::Gtk.Button button62;

	private global::Gtk.VBox vbox24;

	private global::Gtk.Button button66;

	private global::Gtk.Button button70;

	private global::Gtk.Button button74;

	private global::Gtk.VBox vbox18;

	private global::Gtk.Button button57;

	private global::Gtk.Button button63;

	private global::Gtk.VBox vbox26;

	private global::Gtk.Button button67;

	private global::Gtk.Button button71;

	private global::Gtk.Button button75;

	private global::Gtk.VBox vbox20;

	private global::Gtk.Button button59;

	private global::Gtk.Button button64;

	private global::Gtk.VBox vbox28;

	private global::Gtk.Button button68;

	private global::Gtk.Button button72;

	private global::Gtk.Button button76;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 350;
		this.HeightRequest = 500;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox13 = new global::Gtk.VBox();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry();
		this.entry3.HeightRequest = 100;
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.vbox13.Add(this.entry3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.entry3]));
		w1.Position = 0;
		w1.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.hbox39 = new global::Gtk.HBox();
		this.hbox39.WidthRequest = 300;
		this.hbox39.HeightRequest = 400;
		this.hbox39.Name = "hbox39";
		this.hbox39.Spacing = 6;
		// Container child hbox39.Gtk.Box+BoxChild
		this.vbox14 = new global::Gtk.VBox();
		this.vbox14.WidthRequest = 50;
		this.vbox14.HeightRequest = 70;
		this.vbox14.Name = "vbox14";
		this.vbox14.Spacing = 6;
		// Container child vbox14.Gtk.Box+BoxChild
		this.button53 = new global::Gtk.Button();
		this.button53.HeightRequest = 65;
		this.button53.CanFocus = true;
		this.button53.Name = "button53";
		this.button53.UseUnderline = true;
		this.button53.Label = global::Mono.Unix.Catalog.GetString("C");
		this.vbox14.Add(this.button53);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.button53]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.button61 = new global::Gtk.Button();
		this.button61.HeightRequest = 65;
		this.button61.CanFocus = true;
		this.button61.Name = "button61";
		this.button61.UseUnderline = true;
		this.button61.Label = global::Mono.Unix.Catalog.GetString("7");
		this.vbox14.Add(this.button61);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.button61]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.vbox22 = new global::Gtk.VBox();
		this.vbox22.Name = "vbox22";
		this.vbox22.Spacing = 6;
		// Container child vbox22.Gtk.Box+BoxChild
		this.button65 = new global::Gtk.Button();
		this.button65.HeightRequest = 65;
		this.button65.CanFocus = true;
		this.button65.Name = "button65";
		this.button65.UseUnderline = true;
		this.button65.Label = global::Mono.Unix.Catalog.GetString("4");
		this.vbox22.Add(this.button65);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox22[this.button65]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox22.Gtk.Box+BoxChild
		this.button69 = new global::Gtk.Button();
		this.button69.HeightRequest = 65;
		this.button69.CanFocus = true;
		this.button69.Name = "button69";
		this.button69.UseUnderline = true;
		this.button69.Label = global::Mono.Unix.Catalog.GetString("1");
		this.vbox22.Add(this.button69);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox22[this.button69]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox22.Gtk.Box+BoxChild
		this.button73 = new global::Gtk.Button();
		this.button73.HeightRequest = 65;
		this.button73.CanFocus = true;
		this.button73.Name = "button73";
		this.button73.UseUnderline = true;
		this.button73.Label = global::Mono.Unix.Catalog.GetString("radq");
		this.vbox22.Add(this.button73);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox22[this.button73]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox14.Add(this.vbox22);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.vbox22]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.hbox39.Add(this.vbox14);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox39[this.vbox14]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox39.Gtk.Box+BoxChild
		this.hbox41 = new global::Gtk.HBox();
		this.hbox41.Name = "hbox41";
		this.hbox41.Spacing = 6;
		// Container child hbox41.Gtk.Box+BoxChild
		this.vbox16 = new global::Gtk.VBox();
		this.vbox16.WidthRequest = 50;
		this.vbox16.HeightRequest = 0;
		this.vbox16.Name = "vbox16";
		this.vbox16.Spacing = 6;
		// Container child vbox16.Gtk.Box+BoxChild
		this.button55 = new global::Gtk.Button();
		this.button55.WidthRequest = 30;
		this.button55.HeightRequest = 65;
		this.button55.CanFocus = true;
		this.button55.Name = "button55";
		this.button55.UseUnderline = true;
		this.button55.Label = global::Mono.Unix.Catalog.GetString("+/-");
		this.vbox16.Add(this.button55);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.button55]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox16.Gtk.Box+BoxChild
		this.button62 = new global::Gtk.Button();
		this.button62.HeightRequest = 65;
		this.button62.CanFocus = true;
		this.button62.Name = "button62";
		this.button62.UseUnderline = true;
		this.button62.Label = global::Mono.Unix.Catalog.GetString("8");
		this.vbox16.Add(this.button62);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.button62]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox16.Gtk.Box+BoxChild
		this.vbox24 = new global::Gtk.VBox();
		this.vbox24.Name = "vbox24";
		this.vbox24.Spacing = 6;
		// Container child vbox24.Gtk.Box+BoxChild
		this.button66 = new global::Gtk.Button();
		this.button66.HeightRequest = 65;
		this.button66.CanFocus = true;
		this.button66.Name = "button66";
		this.button66.UseUnderline = true;
		this.button66.Label = global::Mono.Unix.Catalog.GetString("5");
		this.vbox24.Add(this.button66);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.button66]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox24.Gtk.Box+BoxChild
		this.button70 = new global::Gtk.Button();
		this.button70.HeightRequest = 65;
		this.button70.CanFocus = true;
		this.button70.Name = "button70";
		this.button70.UseUnderline = true;
		this.button70.Label = global::Mono.Unix.Catalog.GetString("2");
		this.vbox24.Add(this.button70);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.button70]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox24.Gtk.Box+BoxChild
		this.button74 = new global::Gtk.Button();
		this.button74.HeightRequest = 65;
		this.button74.CanFocus = true;
		this.button74.Name = "button74";
		this.button74.UseUnderline = true;
		this.button74.Label = global::Mono.Unix.Catalog.GetString("0");
		this.vbox24.Add(this.button74);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.button74]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox16.Add(this.vbox24);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.vbox24]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.hbox41.Add(this.vbox16);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox41[this.vbox16]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox41.Gtk.Box+BoxChild
		this.vbox18 = new global::Gtk.VBox();
		this.vbox18.WidthRequest = 50;
		this.vbox18.Name = "vbox18";
		this.vbox18.Spacing = 6;
		// Container child vbox18.Gtk.Box+BoxChild
		this.button57 = new global::Gtk.Button();
		this.button57.WidthRequest = 50;
		this.button57.HeightRequest = 65;
		this.button57.CanFocus = true;
		this.button57.Name = "button57";
		this.button57.UseUnderline = true;
		this.button57.Label = global::Mono.Unix.Catalog.GetString("%");
		this.vbox18.Add(this.button57);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.button57]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox18.Gtk.Box+BoxChild
		this.button63 = new global::Gtk.Button();
		this.button63.HeightRequest = 65;
		this.button63.CanFocus = true;
		this.button63.Name = "button63";
		this.button63.UseUnderline = true;
		this.button63.Label = global::Mono.Unix.Catalog.GetString("9");
		this.vbox18.Add(this.button63);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.button63]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox18.Gtk.Box+BoxChild
		this.vbox26 = new global::Gtk.VBox();
		this.vbox26.Name = "vbox26";
		this.vbox26.Spacing = 6;
		// Container child vbox26.Gtk.Box+BoxChild
		this.button67 = new global::Gtk.Button();
		this.button67.HeightRequest = 65;
		this.button67.CanFocus = true;
		this.button67.Name = "button67";
		this.button67.UseUnderline = true;
		this.button67.Label = global::Mono.Unix.Catalog.GetString("6");
		this.vbox26.Add(this.button67);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.button67]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox26.Gtk.Box+BoxChild
		this.button71 = new global::Gtk.Button();
		this.button71.HeightRequest = 65;
		this.button71.CanFocus = true;
		this.button71.Name = "button71";
		this.button71.UseUnderline = true;
		this.button71.Label = global::Mono.Unix.Catalog.GetString("3");
		this.vbox26.Add(this.button71);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.button71]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox26.Gtk.Box+BoxChild
		this.button75 = new global::Gtk.Button();
		this.button75.HeightRequest = 65;
		this.button75.CanFocus = true;
		this.button75.Name = "button75";
		this.button75.UseUnderline = true;
		this.button75.Label = global::Mono.Unix.Catalog.GetString(",");
		this.vbox26.Add(this.button75);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.button75]));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox18.Add(this.vbox26);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.vbox26]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		this.hbox41.Add(this.vbox18);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox41[this.vbox18]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		this.hbox39.Add(this.hbox41);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox39[this.hbox41]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox39.Gtk.Box+BoxChild
		this.vbox20 = new global::Gtk.VBox();
		this.vbox20.WidthRequest = 50;
		this.vbox20.Name = "vbox20";
		this.vbox20.Spacing = 6;
		// Container child vbox20.Gtk.Box+BoxChild
		this.button59 = new global::Gtk.Button();
		this.button59.HeightRequest = 65;
		this.button59.CanFocus = true;
		this.button59.Name = "button59";
		this.button59.UseUnderline = true;
		this.button59.Label = global::Mono.Unix.Catalog.GetString("/");
		this.vbox20.Add(this.button59);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.button59]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox20.Gtk.Box+BoxChild
		this.button64 = new global::Gtk.Button();
		this.button64.HeightRequest = 65;
		this.button64.CanFocus = true;
		this.button64.Name = "button64";
		this.button64.UseUnderline = true;
		this.button64.Label = global::Mono.Unix.Catalog.GetString("x");
		this.vbox20.Add(this.button64);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.button64]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox20.Gtk.Box+BoxChild
		this.vbox28 = new global::Gtk.VBox();
		this.vbox28.Name = "vbox28";
		this.vbox28.Spacing = 6;
		// Container child vbox28.Gtk.Box+BoxChild
		this.button68 = new global::Gtk.Button();
		this.button68.HeightRequest = 65;
		this.button68.CanFocus = true;
		this.button68.Name = "button68";
		this.button68.UseUnderline = true;
		this.button68.Label = global::Mono.Unix.Catalog.GetString("-");
		this.vbox28.Add(this.button68);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.button68]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox28.Gtk.Box+BoxChild
		this.button72 = new global::Gtk.Button();
		this.button72.HeightRequest = 65;
		this.button72.CanFocus = true;
		this.button72.Name = "button72";
		this.button72.UseUnderline = true;
		this.button72.Label = global::Mono.Unix.Catalog.GetString("+");
		this.vbox28.Add(this.button72);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.button72]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vbox28.Gtk.Box+BoxChild
		this.button76 = new global::Gtk.Button();
		this.button76.HeightRequest = 65;
		this.button76.CanFocus = true;
		this.button76.Name = "button76";
		this.button76.UseUnderline = true;
		this.button76.Label = global::Mono.Unix.Catalog.GetString("=");
		this.vbox28.Add(this.button76);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.button76]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		this.vbox20.Add(this.vbox28);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.vbox28]));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		this.hbox39.Add(this.vbox20);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox39[this.vbox20]));
		w30.Position = 2;
		w30.Expand = false;
		w30.Fill = false;
		this.vbox13.Add(this.hbox39);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.hbox39]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		this.Add(this.vbox13);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 500;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
